name: Continous Delivery

# change to merge
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Build docs
      run: npm run build:docs

    - name: Build app
      run: echo "App built"