name: Continuous Integration

on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: 'npm'
    - run: npm ci

    - name: Run Tests
      run: npm test

    - name: Run lint
      run: npm run lint

  comment:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() && (needs.build.result == 'failure') }}
    steps: 
      - uses: actions/checkout@v4
      - name: Comment on the PR
        uses:  thollander/actions-comment-pull-request@v3
        with: 
          message: |
            The CI pipeline run has failed. Please fix any linting and testing errors.
